# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0002_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(default=1, max_length=100, verbose_name='Street name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='streetNumber',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
