# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seals', '0003_auto_20160523_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='streetNumber',
            field=models.IntegerField(max_length=3, verbose_name='Street number'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Company'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
