# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0004_auto_20160523_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('size', models.IntegerField(max_length=4)),
                ('installedInVessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Vessel')),
            ],
        ),
    ]
