# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seals', '0005_seal'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='contactPerson',
        ),
        migrations.AlterField(
            model_name='seal',
            name='installedInVessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Vessel', verbose_name='Installed in vessel'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.contactPerson'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Company'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
