# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0006_auto_20160523_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_contactperson', to='seals.contactPerson'),
        ),
    ]
