# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0007_auto_20160523_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='streetNumber',
            field=models.IntegerField(verbose_name='Street number'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='size',
            field=models.IntegerField(verbose_name='Seal size'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='contactPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vessel_contactperson', to='seals.contactPerson'),
        ),
    ]
