# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0008_auto_20160527_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='contactPerson',
        ),
    ]
