# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0009_remove_vessel_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='contact',
            field=models.ManyToManyField(to='seals.contactPerson'),
        ),
    ]
