# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0010_vessel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 5, 29, 15, 29, 40, 176179, tzinfo=utc)),
        ),
    ]
