# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0011_seal_created'),
    ]

    operations = [
            migrations.RenameField('Seal','installedInVessel','installedinvessel'),
    ]
