# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0012_auto_20160529_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 5, 30, 7, 28, 24, 778912, tzinfo=utc), verbose_name='Created'),
        ),
    ]
