# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0013_auto_20160530_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='created',
            field=models.DateField(verbose_name='Created'),
        ),
    ]
