# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0014_auto_20160530_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Action date')),
            ],
        ),
        migrations.CreateModel(
            name='CreateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('remarks', models.CharField(max_length=1000, verbose_name='Remarks')),
            ],
        ),
        migrations.AlterField(
            model_name='seal',
            name='serial_number',
            field=models.CharField(max_length=10, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='contact',
            field=models.ManyToManyField(to='seals.contactPerson', verbose_name='Contact person(s)'),
        ),
        migrations.AddField(
            model_name='action',
            name='actiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.CreateReport', verbose_name='Action type'),
        ),
        migrations.AddField(
            model_name='action',
            name='relatedtoseal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Seal', verbose_name='Related to seal'),
        ),
    ]
