# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0015_auto_20160530_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('remarks', models.CharField(max_length=1000, verbose_name='Remarks')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='actiontype',
        ),
        migrations.DeleteModel(
            name='CreateReport',
        ),
        migrations.AddField(
            model_name='report',
            name='relatedtoaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Action', verbose_name='Related to action'),
        ),
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seals.ActionType', verbose_name='Action type'),
            preserve_default=False,
        ),
    ]
