# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0016_auto_20160530_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='relatedtoseal',
        ),
        migrations.RemoveField(
            model_name='report',
            name='relatedtoaction',
        ),
        migrations.AddField(
            model_name='report',
            name='relatedtoseal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seals.Seal', verbose_name='Related to seal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
    ]
