# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:37
from __future__ import unicode_literals
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0017_auto_20160530_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
