# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0019_auto_20160530_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execute_date', models.DateTimeField()),
                ('remarks', models.CharField(max_length=1000, verbose_name='Remarks')),
                ('relatedtoreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Report', verbose_name='Related to report')),
                ('relatedtoseal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Seal', verbose_name='Related to seal')),
            ],
        ),
    ]
