# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0021_auto_20160530_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='execute_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
