# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0022_auto_20160607_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
