# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0024_auto_20160610_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='created',
            field=models.DateTimeField(verbose_name='Created'),
        ),
    ]
