# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0026_auto_20160612_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='installedinvessel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seals.Vessel', verbose_name='Installed in vessel'),
            preserve_default=False,
        ),
    ]
