# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0027_auto_20160612_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sealstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='seal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seals.Sealstatus'),
            preserve_default=False,
        ),
    ]
