# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0028_auto_20160617_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='seal',
            name='sealtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seals.Type'),
            preserve_default=False,
        ),
    ]
