# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0029_auto_20160620_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='sealtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seals.Type', verbose_name='Type'),
        ),
    ]
