# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='draught_shaft',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Shaft centerline draught'),
        ),
        migrations.AddField(
            model_name='advise',
            name='rpm',
            field=models.IntegerField(default=0, verbose_name='Shaft rotational speed (RPM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='shaft_size_aft',
            field=models.IntegerField(default=0, verbose_name='Shaft diameter aft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='shaft_size_forward',
            field=models.IntegerField(default=0, verbose_name='Shaft diameter forward'),
            preserve_default=False,
        ),
    ]
