# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0002_auto_20160531_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='aftseal',
            field=models.BooleanField(default=0, verbose_name='Aft seal needed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='eal',
            field=models.NullBooleanField(verbose_name='EAL oil used'),
        ),
        migrations.AddField(
            model_name='advise',
            name='forwardseal',
            field=models.BooleanField(default=0, verbose_name='Forward seal needed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advise',
            name='draught_shaft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Shaft centerline draught'),
            preserve_default=False,
        ),
    ]
