# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0003_auto_20160531_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advise',
            name='aftseal',
            field=models.BooleanField(default=False, verbose_name='Aft seal needed'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='eal',
            field=models.BooleanField(default=False, verbose_name='EAL oil used'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='forwardseal',
            field=models.BooleanField(default=False, verbose_name='Forward seal needed'),
        ),
    ]
