# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0004_auto_20160531_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advise',
            name='shaft_size_aft',
        ),
        migrations.RemoveField(
            model_name='advise',
            name='shaft_size_forward',
        ),
        migrations.AddField(
            model_name='advise',
            name='shaft_size',
            field=models.IntegerField(default=0, verbose_name='Shaft diameter aft (mm)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advise',
            name='draught_shaft',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Shaft centerline draught (m)'),
        ),
    ]
