# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0005_auto_20160531_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='draught_shaft_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Shaft centerline draught min (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='draught_shaft_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Shaft centerline draught max (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='liner_centering',
            field=models.CharField(choices=[('hub', 'Hub'), ('shaft', 'Shaft')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='advise',
            name='shaft_size',
            field=models.IntegerField(verbose_name='Shaft diameter (mm)'),
        ),
    ]
