# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0006_auto_20160531_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='oring',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='advise',
            name='liner_centering',
            field=models.CharField(choices=[('hub', 'Hub'), ('shaft', 'Shaft')], default='', max_length=20),
        ),
    ]
