# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0007_auto_20160531_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='anode',
            field=models.BooleanField(default=False, verbose_name='Protection against corrosion using cathodic protection?'),
        ),
        migrations.AddField(
            model_name='advise',
            name='athmos',
            field=models.BooleanField(default=False, verbose_name='Include SUPREME Athmos?'),
        ),
        migrations.AddField(
            model_name='advise',
            name='sandy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10, verbose_name='Will the seal be applied in a sandy/dirty environment?'),
        ),
        migrations.AddField(
            model_name='advise',
            name='ventus',
            field=models.BooleanField(default=False, verbose_name='Include SUPREME Ventus?'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='eal',
            field=models.BooleanField(default=False, verbose_name='EAL oil used?'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='oring',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, verbose_name='O-ring between shaft & liner (O-ring commonly used for FPP)'),
        ),
    ]
