# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0008_auto_20160601_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='netcutters',
            field=models.CharField(choices=[('clockwise', 'Clockwise'), ('counterclockwise', 'Counterclockwise'), ('two', 'Two of each on one seal')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='advise',
            name='wirewinder',
            field=models.BooleanField(default=False, verbose_name='Protection against wires (wire-winder)?'),
        ),
    ]
