# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0009_auto_20160601_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='cpp_fpp',
            field=models.CharField(choices=[('fpp', 'Fixed pitch'), ('cpp', 'Controllable pitch')], default='fpp', max_length=10, verbose_name='Fixed or controllable pitch propellor'),
            preserve_default=False,
        ),
    ]
