# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0010_advise_cpp_fpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='product',
            field=models.CharField(choices=[('supreme', 'Supreme'), ('liquidyne', 'Liquidyne'), ('sublime', 'Sublime'), ('bearing', 'Bearings'), ('other', 'Other')], default='supreme', max_length=10),
            preserve_default=False,
        ),
    ]
