# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0011_advise_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advise',
            name='product',
        ),
    ]
