# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0012_remove_advise_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='shaft_size_forward',
            field=models.IntegerField(default=1, verbose_name='Forward shaft diameter (mm)'),
            preserve_default=False,
        ),
    ]
