# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0014_auto_20160623_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='forward_pcd_centering',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='forward seal centering edge PCD [mm]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='forward_pcd_flange',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='forward seal flange PCD [mm]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='forward_pcd_liner',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='forward seal liner PCD [mm]'),
            preserve_default=False,
        ),
    ]
