# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0015_auto_20160623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advise',
            name='shaft_size_forward',
            field=models.IntegerField(blank=True, null=True, verbose_name='Forward shaft diameter (mm)'),
        ),
    ]
