# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0017_auto_20160623_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='type_approval',
            field=models.CharField(default=1, max_length=200, verbose_name='Type approval required (specify which or leave blank)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='vgp',
            field=models.BooleanField(default=False, verbose_name='Compliance with VGP (American waters)'),
        ),
    ]
