# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0019_auto_20160623_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='aft_liner_centering_edge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Aft seal liner centering edge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advise',
            name='aft_pcd_centering',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Aft seal flange ring centering edge [mm]'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='aft_pcd_flange',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Aft seal flange ring PCD [mm]'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='shaft_size',
            field=models.IntegerField(verbose_name='Shaft diameter aft seal (mm)'),
        ),
    ]
