# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0020_auto_20160623_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='aft_built_in_length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Built in length [mm]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advise',
            name='aft_liner_centering_edge',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Aft seal liner centering edge [mm]'),
        ),
    ]
