# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0023_auto_20160623_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='advise',
            name='forward_pcd_centering',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='forward seal centering edge [mm]'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='hml_forward',
            field=models.BooleanField(default=False, verbose_name='HML wear resistant liner coating?'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='oring',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, verbose_name='O-ring between shaft & liner?'),
        ),
        migrations.AlterField(
            model_name='advise',
            name='type_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor.ApprovalType', verbose_name='Type approval required (specify which or leave blank)'),
        ),
    ]
