# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor', '0024_auto_20160624_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaltype',
            name='name',
        ),
        migrations.AddField(
            model_name='approvaltype',
            name='certificateNo',
            field=models.CharField(default=1, max_length=100, verbose_name='Certificate No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvaltype',
            name='className',
            field=models.CharField(default=1, max_length=100, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvaltype',
            name='issueDate',
            field=models.DateField(default=datetime.date(2016, 6, 24), verbose_name='Date of issue'),
        ),
    ]
