# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
