# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_seal_vessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parts_to_replace', models.ManyToManyField(to='erp.sealComponent')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Seal')),
            ],
        ),
    ]
