# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_servicereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='sealComponentChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_component', to='erp.Part')),
                ('old_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_component', to='erp.Part')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Seal')),
            ],
        ),
    ]
