# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_remove_sealcomponentchange_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealcomponentchange',
            name='service_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.serviceReport'),
            preserve_default=False,
        ),
    ]
