# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seal',
            old_name='sealType',
            new_name='seal_type',
        ),
        migrations.RenameField(
            model_name='seal',
            old_name='xNumber',
            new_name='x_number',
        ),
    ]
