# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='imo',
            field=models.CharField(default=1, max_length=10, verbose_name='IMO number'),
            preserve_default=False,
        ),
    ]
