# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_vessel_imo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='erp.contactPerson'),
        ),
    ]
