# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20160704_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmcomponentchange',
            name='seal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Seal'),
            preserve_default=False,
        ),
    ]
