# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_vessel_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='superintendant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.contactPerson'),
            preserve_default=False,
        ),
    ]
