# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20160702_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='parts',
            field=models.ManyToManyField(to='erp.Part'),
        ),
    ]
