# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_servicereport_superintendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='date_installed',
            field=models.DateField(default='2016-01-01', verbose_name='Installed date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seal',
            name='date_removed',
            field=models.DateField(default='2017-01-01', verbose_name='Removed date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='contacts',
            field=models.ManyToManyField(to='erp.contactPerson'),
        ),
    ]
