# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_sealcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='components',
            field=models.ManyToManyField(to='erp.sealComponent'),
        ),
    ]
