# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='mechanics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Mechanic'),
            preserve_default=False,
        ),
    ]
