# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20160708_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='date_removed',
            field=models.DateField(blank=True, null=True, verbose_name='Removed date'),
        ),
    ]
