# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_seal_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seal',
            name='components',
        ),
        migrations.AddField(
            model_name='sealcomponent',
            name='seal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Seal'),
            preserve_default=False,
        ),
    ]
