# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20160702_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealcomponent',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.sealComponent', verbose_name='Replaced by component'),
        ),
        migrations.AddField(
            model_name='sealcomponent',
            name='status',
            field=models.CharField(choices=[('as-installed', 'As installed'), ('replaced', 'Replaced (due to maintainance)'), ('removed', 'Removed and not replaced')], default='as-installed', max_length=20),
            preserve_default=False,
        ),
    ]
