# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_servicereport_mechanics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='mechanics',
        ),
        migrations.AddField(
            model_name='servicereport',
            name='mechanics',
            field=models.ManyToManyField(to='erp.Mechanic'),
        ),
    ]
