# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20160703_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='size',
            field=models.IntegerField(default=125),
            preserve_default=False,
        ),
    ]
