# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20160704_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='date',
            field=models.DateField(default='2016-07-04'),
            preserve_default=False,
        ),
    ]
