# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0009_auto_20160726_1031'),
        ('erp', '0009_remove_servicereport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aft_defaults',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.AftSealOptions'),
        ),
        migrations.AddField(
            model_name='company',
            name='fwd_defaults',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.FwdSealOptions'),
        ),
    ]
