# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20160728_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='location',
            field=models.CharField(default='no idea', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicereport',
            name='ls_number',
            field=models.CharField(default='ls123', max_length=20),
            preserve_default=False,
        ),
    ]
