# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20160808_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servicereport',
            name='reason',
            field=models.ManyToManyField(to='erp.Reason'),
        ),
    ]
