# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SealSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type such as 'STA'", max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='seal',
            name='seal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealType'),
        ),
        migrations.AddField(
            model_name='seal',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealSize'),
        ),
    ]
