# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0017_auto_20160808_1952'),
        ('isah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aft_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.AftSealOptions')),
                ('fwd_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.FwdSealOptions')),
            ],
        ),
    ]
