# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0002_sealcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sealcompany',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
