# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0003_auto_20160814_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealcompany',
            name='aft_preferences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.AftSealOptions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sealcompany',
            name='fwd_preferences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.FwdSealOptions'),
            preserve_default=False,
        ),
    ]
