# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0004_auto_20160814_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealVessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('imo_number', models.CharField(max_length=10, verbose_name='IMO number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany')),
            ],
        ),
        migrations.AlterField(
            model_name='seal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='seal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='serial_number',
            field=models.CharField(max_length=15, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealSize', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
