# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0005_auto_20160814_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isah.SealVessel', verbose_name='Vessel'),
        ),
        migrations.AlterField(
            model_name='sealvessel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany', verbose_name='Company'),
        ),
    ]
