# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0006_auto_20160814_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealcompany',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sealcompany',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sealcompany',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
