# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0007_auto_20160815_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealcompany',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sealcompany',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='sealcompany',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='sealcompany',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
