# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0010_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='position',
            field=models.CharField(default='Skipper', max_length=100, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
