# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0011_contactperson_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Start date')),
                ('date_to', models.DateField(verbose_name='End date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany', verbose_name='Company')),
                ('ls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.LS', verbose_name='LS order no.')),
                ('superintendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.ContactPerson', verbose_name='Contact person')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isah.SealVessel', verbose_name='Vessel')),
            ],
        ),
    ]
