# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0012_servicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ls',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isah.SealCompany', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
