# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0013_ls_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='side',
            field=models.CharField(blank=True, choices=[('PS', 'Port side'), ('SB', 'Starboard')], help_text='At which side is the seal installed or leave blank in case of a single propellor', max_length=10, null=True, verbose_name='Side'),
        ),
    ]
