# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0014_seal_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='side',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('PS', 'Port side'), ('SB', 'Starboard')], default='N/A', help_text='At which side is the seal installed or leave blank in case of a single propellor', max_length=10, verbose_name='Side'),
            preserve_default=False,
        ),
    ]
