# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0016_servicereport_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ls',
            name='seals',
            field=models.ManyToManyField(null=True, to='isah.Seal', verbose_name='Related seals'),
        ),
    ]
