# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0018_auto_20160821_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='remarks',
            field=models.CharField(blank=True, help_text='General (not related to a seal) remarks', max_length=2000, verbose_name='Remarks'),
        ),
    ]
