# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0020_servicereport_vessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Part name', max_length=100)),
                ('applicable_sizes', models.ManyToManyField(to='isah.SealSize', verbose_name='Applicable sizes')),
            ],
        ),
    ]
