# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0021_sealpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Part name', max_length=100)),
                ('applicable_sizes', models.ManyToManyField(to='isah.SealSize', verbose_name='Applicable sizes')),
            ],
        ),
        migrations.RemoveField(
            model_name='sealpart',
            name='applicable_sizes',
        ),
        migrations.RemoveField(
            model_name='sealpart',
            name='name',
        ),
        migrations.AddField(
            model_name='seal',
            name='parts',
            field=models.ManyToManyField(to='isah.SealPart', verbose_name='Parts'),
        ),
        migrations.AddField(
            model_name='sealpart',
            name='number_of_parts',
            field=models.IntegerField(default=1, verbose_name='Number of this part in the seal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ls',
            name='seals',
            field=models.ManyToManyField(blank=True, to='isah.Seal', verbose_name='Related seals'),
        ),
        migrations.AddField(
            model_name='sealpart',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isah.Part', verbose_name='Part'),
            preserve_default=False,
        ),
    ]
