# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0022_auto_20160917_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seal',
            name='parts',
        ),
        migrations.AddField(
            model_name='seal',
            name='as_installed_parts',
            field=models.ManyToManyField(to='isah.SealPart', verbose_name='As installed parts'),
        ),
    ]
