# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0024_remove_seal_as_installed_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealpart',
            name='seal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isah.Seal', verbose_name='Related seal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sealpart',
            name='status',
            field=models.CharField(choices=[('as_installed', 'As installed'), ('as_maintained', 'As maintained')], default='as_installed', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
