# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seals', '0030_auto_20160624_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='generalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_fpp', models.CharField(choices=[('fpp', 'Fixed pitch'), ('cpp', 'Controllable pitch')], max_length=10, verbose_name='Fixed or controllable pitch propellor')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.Application')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seals.Company', verbose_name='Company (or leave blank)')),
            ],
        ),
    ]
