# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0002_auto_20160624_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='generalInformation',
            new_name='sealadvisorWizard',
        ),
    ]
