# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0006_auto_20160624_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeaftshaftinformation',
            name='aft_centering_edge',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Aft seal flange ring centering edge [mm]'),
        ),
        migrations.AlterField(
            model_name='supremeaftshaftinformation',
            name='aft_pcd_flange',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Aft seal flange ring PCD [mm]'),
        ),
        migrations.AlterField(
            model_name='supremeaftshaftinformation',
            name='aft_pcd_liner',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Aft seal liner PCD [mm]'),
        ),
        migrations.AlterField(
            model_name='supremefwdshaftinformation',
            name='fwd_centering_edge',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='forward seal centering edge [mm]'),
        ),
        migrations.AlterField(
            model_name='supremefwdshaftinformation',
            name='fwd_pcd_flange',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='forward seal flange PCD [mm]'),
        ),
        migrations.AlterField(
            model_name='supremefwdshaftinformation',
            name='fwd_pcd_liner',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='forward seal liner PCD [mm]'),
        ),
    ]
