# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0009_auto_20160625_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='environmentalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eal', models.BooleanField(default=False, verbose_name='EAL oil used?')),
                ('vgp', models.BooleanField(default=False, verbose_name='Compliance with VGP (American waters)')),
            ],
        ),
    ]
