# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0011_supremeadvise_environmental'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalinformation',
            name='zero_leakage',
            field=models.BooleanField(default=False, verbose_name='Zero leakage (ventus/athmos)'),
        ),
    ]
