# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0013_environmentalinformation_zero_leakage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalinformation',
            name='zero_leakage_type',
            field=models.CharField(blank=True, choices=[('ventus', 'Ventus'), ('athmos', 'Athmos')], max_length=20, verbose_name='Zero leakage system'),
        ),
    ]
