# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0014_auto_20160625_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeaftshaftinformation',
            name='aft_shaft_size',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='Aft shaft diameter (mm)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supremefwdshaftinformation',
            name='fwd_shaft_size',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='Forward shaft diameter (mm)'),
            preserve_default=False,
        ),
    ]
