# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0015_auto_20160625_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeadvise',
            name='rpm',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Shaft rotational speed (RPM)'),
        ),
    ]
