# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0017_auto_20160627_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='sandy',
            field=models.BooleanField(default=False, verbose_name='Will the seal be applied in a sandy/dirty environment?'),
        ),
        migrations.AlterField(
            model_name='environmentalinformation',
            name='eal',
            field=models.BooleanField(default=False, verbose_name='EAL oil used (in case of retrofit)?'),
        ),
        migrations.AlterField(
            model_name='environmentalinformation',
            name='zero_leakage_type',
            field=models.CharField(blank=True, choices=[('ventus', 'Ventus'), ('athmos', 'Athmos')], max_length=20, verbose_name='Zero leakage system (Athmos/Ventus)'),
        ),
    ]
