# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0019_remove_supremeadvise_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supremeadvise',
            name='sandy',
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='cpp_fpp',
            field=models.CharField(blank=True, choices=[('fpp', 'Fixed pitch'), ('cpp', 'Controllable pitch')], max_length=10, null=True, verbose_name='Fixed or controllable pitch propellor'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='draught_shaft',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Shaft draught (aft) [m]'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='rpm',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Shaft revolutions per minute [RPM]'),
        ),
    ]
