# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0023_auto_20160629_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AftSealOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seaguard', models.BooleanField(default=False, verbose_name='Seaguard')),
                ('linerCentering', models.CharField(choices=[('shaft', 'Shaft centered'), ('hub', 'Hub centered')], max_length=20, verbose_name='Liner centering')),
                ('oring', models.BooleanField(default=True, verbose_name='O-ring between liner and shaft')),
                ('distanceRing', models.BooleanField(default=False, verbose_name='Distance ring')),
                ('dirtBarrier', models.BooleanField(default=False, verbose_name='Dirt barrier')),
                ('wireWinders', models.BooleanField(default=False, verbose_name='Wire winders')),
                ('netCutters', models.BooleanField(default=False, verbose_name='Net cutters')),
                ('hastelloy', models.BooleanField(default=False, verbose_name='Hastelloy springs')),
            ],
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='rpm',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Nominal shaft revolutions per minute [RPM]'),
        ),
    ]
