# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0029_auto_20160629_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftsealoptions',
            name='oring',
            field=models.BooleanField(default=False, verbose_name='O-ring between liner and shaft'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='draught_shaft',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Draught to (aft) shaft centerline [m]'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='rpm',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='RPM'),
        ),
    ]
