# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0030_auto_20160630_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftsealoptions',
            name='air',
            field=models.BooleanField(default=False, verbose_name='Use an air type system to equalize the pressure and collect any leakage (Ventus/Athmos)'),
        ),
    ]
