# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 09:52
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('isah', '0006_auto_20160814_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealcompany',
            name='address',
            field=address.models.AddressField(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
            preserve_default=False,
        ),
    ]
