# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isah', '0007_sealcompany_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sealcompany',
            name='address',
        ),
    ]
