# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0002_auto_20160711_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftsealoptions',
            name='anode',
            field=models.BooleanField(default=False, verbose_name='Use kathodic protection to prevent corrosion'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='aft_build_in_length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Aft seal build in length [mm]'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='fwd_build_in_length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Forward seal build in length [mm]'),
        ),
    ]
