# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0004_auto_20160624_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sealadvisorWizard',
            new_name='supremeAdvise',
        ),
    ]
