# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0005_supremeadvise_vgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftsealoptions',
            name='air',
            field=models.BooleanField(default=False, verbose_name='Ventus/Athmos (depending on draught)'),
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='anode',
            field=models.BooleanField(default=False, verbose_name='Kathodic protection'),
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='dirtBarrier',
            field=models.BooleanField(default=False, verbose_name='Dirt barrier'),
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='hml',
            field=models.BooleanField(default=False, verbose_name='Hard metal layer (HML)'),
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='seaguard',
            field=models.BooleanField(default=False, verbose_name='Seaguard (backup oil repellant lip-seal)'),
        ),
    ]
