# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0006_auto_20160718_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='number_of_shafts',
            field=models.IntegerField(default=1, verbose_name='Number of shafts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='aft_seal',
            field=models.BooleanField(default=False, verbose_name='Aft seal'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='fwd_seal',
            field=models.BooleanField(default=False, verbose_name='Forward seal'),
        ),
    ]
