# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0007_auto_20160726_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('bureau', models.CharField(max_length=100, verbose_name='Classification bureau')),
            ],
        ),
        migrations.AddField(
            model_name='supremeadvise',
            name='classCertificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.Certificate', verbose_name='Class certificate (specify which or leave blank)'),
        ),
    ]
