# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0008_auto_20160726_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='linerCentering',
            field=models.CharField(default=1, max_length=20, verbose_name='Liner centering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='linerCentering',
            field=models.CharField(max_length=20, verbose_name='Liner centering'),
        ),
    ]
