# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0008_auto_20160624_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supremeadvise',
            old_name='aft_seal_information',
            new_name='aft_shaft_information',
        ),
        migrations.RenameField(
            model_name='supremeadvise',
            old_name='fwd_seal_information',
            new_name='fwd_shaft_information',
        ),
    ]
