# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0009_auto_20160726_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftsealoptions',
            name='fkm',
            field=models.BooleanField(default=False, verbose_name='FKM lip-seals'),
        ),
        migrations.AlterField(
            model_name='fwdsealoptions',
            name='fkm',
            field=models.BooleanField(default=False, verbose_name='FKM lip-seals'),
        ),
    ]
