# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0010_environmentalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='environmental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.environmentalInformation'),
        ),
    ]
