# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0011_remove_aftsealoptions_linercentering'),
    ]

    operations = [
        migrations.AddField(
            model_name='fwdsealoptions',
            name='high_pressure',
            field=models.BooleanField(default=False, verbose_name='High pressure'),
        ),
    ]
