# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0012_environmentalinformation_zero_leakage'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalinformation',
            name='zero_leakage_type',
            field=models.CharField(choices=[('ventus', 'Ventus'), ('athmos', 'Athmos')], default=1, max_length=20, verbose_name='Zero leakage system'),
            preserve_default=False,
        ),
    ]
