# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0013_auto_20160728_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeadvise',
            name='number_of_shafts',
            field=models.IntegerField(verbose_name='Number of shafts per vessel'),
        ),
    ]
