# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20160728_0851'),
        ('sealadvisor2', '0015_auto_20160802_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Company'),
            preserve_default=False,
        ),
    ]
