# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0016_auto_20160625_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('className', models.CharField(max_length=100, verbose_name='Class')),
                ('certificateNo', models.CharField(max_length=100, verbose_name='Certificate No.')),
            ],
        ),
        migrations.AddField(
            model_name='supremeadvise',
            name='typeApproval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.Class', verbose_name='Type approval required (specify which or leave blank)'),
        ),
    ]
