# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0021_auto_20160628_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeadvise',
            name='aftSize',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Aft shaft diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='aft_seal',
            field=models.BooleanField(default=False, verbose_name='Aft seal.'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='fwdSize',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Forward shaft diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='supremeadvise',
            name='fwd_seal',
            field=models.BooleanField(default=False, verbose_name='Forward seal.'),
        ),
    ]
