# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0025_supremeadvise_aft'),
    ]

    operations = [
        migrations.CreateModel(
            name='environmentalOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgp', models.BooleanField(default=False, verbose_name='Has to comply with VGP regulations')),
                ('oil', models.CharField(choices=[('mineral', 'Mineral oil'), ('eal', 'EAL oil (bio-oil)')], max_length=20, verbose_name='What kind of oil is used')),
                ('air', models.BooleanField(default=False, verbose_name='Use an air type system (Ventus/Athmos) to comply with VGP and reduce the pressure on the lip seals')),
            ],
        ),
        migrations.AlterField(
            model_name='aftsealoptions',
            name='dirtBarrier',
            field=models.BooleanField(default=False, verbose_name='Dirt barrier > is the seal used in a dirty/sandy environment'),
        ),
    ]
