# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0027_supremeadvise_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftsealoptions',
            name='hml',
            field=models.BooleanField(default=False, verbose_name='Hard metal layer to prevent liner wear (HML)'),
        ),
    ]
