# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0032_fwdsealoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeadvise',
            name='fwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sealadvisor2.FwdSealOptions'),
        ),
        migrations.AlterField(
            model_name='environmentaloptions',
            name='oil',
            field=models.CharField(choices=[('mineral', 'Mineral oil'), ('eal', 'EAL oil (bio degradable oil)')], max_length=20, verbose_name='What kind of oil is used'),
        ),
    ]
