# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealadvisor2', '0033_auto_20160701_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaloptions',
            name='oilType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What type of oil is used'),
        ),
    ]
